version: '3.6'
services:
  restapi:
    build:
      context: ./mpiot-back
    depends_on:
      - messenger
    environment:
      - MESSENGER_HOST=messenger
      - MESSENGER_PORT=6379
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./storage:/usr/src/app/storage
  messenger:
    image: redis
    ports: 
      - "6379:6379"
    volumes:
      - messenger_data:/data
  trainer:
    build:
      context: ./mpiot-trainer/container
    depends_on:
      - messenger
    environment:
      - MESSENGER_HOST=messenger
      - MESSENGER_PORT=6379
    volumes:
      - ./uploads:/uploads
      - ./shared:/shared
      - ./mpiot-trainer/service:/service
    
volumes:
  messenger_data: